Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ben/miniconda3/envs/pyCATHY_doc/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
simu.update_veg_map()

df_soil, _ = simu.read_inputs('soil')
#simu.update_soil()
#simu.soil

df_soil

df_soil['PERMX']


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m simu[38;5;241m.[39mupdate_veg_map()
[0;32m----> 3[0m df_soil, _ [38;5;241m=[39m [43msimu[49m[38;5;241;43m.[39;49m[43mread_inputs[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43msoil[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      4[0m [38;5;66;03m#simu.update_soil()[39;00m
[1;32m      5[0m [38;5;66;03m#simu.soil[39;00m
[1;32m      7[0m df_soil

File [0;32m~/Documents/GitHub/BenjMy/pycathy_wrapper/pyCATHY/cathy_tools.py:3715[0m, in [0;36mCATHY.read_inputs[0;34m(self, filename, **kwargs)[0m
[1;32m   3712[0m [38;5;28;01melse[39;00m:
[1;32m   3713[0m     MAXVEG [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mMAXVEG
[0;32m-> 3715[0m df [38;5;241m=[39m [43min_CT[49m[38;5;241;43m.[39;49m[43mread_soil[49m[43m([49m
[1;32m   3716[0m [43m    [49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mworkdir[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mproject_name[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43minput[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mfilename[49m[43m)[49m[43m,[49m
[1;32m   3717[0m [43m    [49m[43mdem_parm[49m[43m,[49m
[1;32m   3718[0m [43m    [49m[43mMAXVEG[49m[38;5;241;43m=[39;49m[43mMAXVEG[49m[43m,[49m
[1;32m   3719[0m [43m[49m[43m)[49m
[1;32m   3720[0m [38;5;66;03m# df[0][39;00m
[1;32m   3721[0m [38;5;28;01mreturn[39;00m df

File [0;32m~/Documents/GitHub/BenjMy/pycathy_wrapper/pyCATHY/importers/cathy_inputs.py:387[0m, in [0;36mread_soil[0;34m(soilfile, dem_parm, MAXVEG)[0m
[1;32m    384[0m         name_zone[38;5;241m.[39mappend([38;5;28mstr[39m(dz))
[1;32m    386[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(soil) [38;5;241m!=[39m [38;5;28mlen[39m(name_str):
[0;32m--> 387[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    388[0m         [38;5;124m"[39m[38;5;124mInconsistent number of zones/layers with respect to the number of soil lines[39m[38;5;124m"[39m
[1;32m    389[0m     )
[1;32m    390[0m df_soil [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(soil, [name_str, name_zone], soil_header)
[1;32m    391[0m df_soil[38;5;241m.[39mindex[38;5;241m.[39mset_names([38;5;124m"[39m[38;5;124mstr[39m[38;5;124m"[39m, level[38;5;241m=[39m[38;5;241m0[39m, inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[0;31mValueError[0m: Inconsistent number of zones/layers with respect to the number of soil lines
ValueError: Inconsistent number of zones/layers with respect to the number of soil lines

